pimcore:
    objects:
        custom_layouts:
            definitions:
                304cdad9-03a6-47bd-853d-4df187f02ab6:
                    id: 304cdad9-03a6-47bd-853d-4df187f02ab6
                    name: siping
                    description: ''
                    creationDate: 1699275302
                    modificationDate: 1699275327
                    userOwner: 2
                    classId: '3'
                    layoutDefinitions:
                        name: pimcore_root
                        type: null
                        region: null
                        title: null
                        width: 0
                        height: 0
                        collapsible: false
                        collapsed: false
                        bodyStyle: null
                        datatype: layout
                        children:
                            -
                                name: Layout
                                type: null
                                region: null
                                title: ''
                                width: ''
                                height: ''
                                collapsible: false
                                collapsed: false
                                bodyStyle: ''
                                datatype: layout
                                children:
                                    -
                                        name: Desc
                                        title: Desc
                                        tooltip: ''
                                        mandatory: false
                                        noteditable: false
                                        index: false
                                        locked: false
                                        style: ''
                                        permissions: null
                                        fieldtype: textarea
                                        relationType: false
                                        invisible: false
                                        visibleGridView: false
                                        visibleSearch: false
                                        maxLength: null
                                        showCharCount: false
                                        excludeFromSearchIndex: false
                                        height: ''
                                        width: ''
                                        datatype: data
                                locked: false
                                fieldtype: panel
                                layout: null
                                border: false
                                icon: ''
                                labelWidth: 100
                                labelAlign: left
                        locked: false
                        fieldtype: panel
                        layout: null
                        border: false
                        icon: null
                        labelWidth: 100
                        labelAlign: left
                    default: 0
