pimcore:
    objects:
        custom_layouts:
            definitions:
                9b363f60-dd3d-43f1-ac87-ea359014df56:
                    id: 9b363f60-dd3d-43f1-ac87-ea359014df56
                    name: helllo
                    description: ''
                    creationDate: 1700560243
                    modificationDate: 1700560321
                    userOwner: 2
                    classId: '6'
                    layoutDefinitions:
                        name: pimcore_root
                        type: null
                        region: null
                        title: null
                        width: 0
                        height: 0
                        collapsible: false
                        collapsed: false
                        bodyStyle: null
                        datatype: layout
                        children:
                            -
                                name: Layout
                                type: null
                                region: null
                                title: null
                                width: 0
                                height: 0
                                collapsible: false
                                collapsed: false
                                bodyStyle: null
                                datatype: layout
                                children:
                                    -
                                        name: localizedfields
                                        title: ''
                                        tooltip: null
                                        mandatory: false
                                        noteditable: false
                                        index: false
                                        locked: false
                                        style: null
                                        permissions: null
                                        fieldtype: localizedfields
                                        relationType: false
                                        invisible: false
                                        visibleGridView: true
                                        visibleSearch: true
                                        children:
                                            -
                                                name: name
                                                title: Name
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: input
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                defaultValue: null
                                                columnLength: 190
                                                regex: ''
                                                regexFlags: {  }
                                                unique: false
                                                showCharCount: false
                                                width: ''
                                                defaultValueGenerator: ''
                                                datatype: data
                                            -
                                                name: desc
                                                title: Desc
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: textarea
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                maxLength: null
                                                showCharCount: false
                                                excludeFromSearchIndex: false
                                                height: ''
                                                width: ''
                                                datatype: data
                                            -
                                                name: image
                                                title: Image
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: image
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                uploadPath: ''
                                                width: ''
                                                height: ''
                                                datatype: data
                                            -
                                                name: price
                                                title: Price
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: numeric
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                defaultValue: null
                                                integer: false
                                                unsigned: false
                                                minValue: null
                                                maxValue: null
                                                unique: false
                                                decimalSize: null
                                                decimalPrecision: null
                                                width: ''
                                                defaultValueGenerator: ''
                                                datatype: data
                                            -
                                                name: qty
                                                title: Qty
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: slider
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                minValue: null
                                                maxValue: null
                                                vertical: false
                                                increment: null
                                                decimalPrecision: null
                                                height: ''
                                                width: ''
                                                datatype: data
                                        region: null
                                        layout: null
                                        maxTabs: null
                                        border: false
                                        provideSplitView: false
                                        tabPosition: top
                                        hideLabelsWhenTabsReached: null
                                        permissionView: null
                                        permissionEdit: null
                                        labelWidth: 100
                                        labelAlign: left
                                        datatype: data
                                locked: false
                                fieldtype: panel
                                layout: null
                                border: false
                                icon: null
                                labelWidth: 100
                                labelAlign: left
                        locked: false
                        fieldtype: panel
                        layout: null
                        border: false
                        icon: null
                        labelWidth: 100
                        labelAlign: left
                    default: 1
