services:
    TestBundle\Service\DataCustomService:
        public: true
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    TestBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']
  
  # COMMANDS
    #

    # auto-register all commands as services
    TestBundle\Command\:
        resource: '../src/Command/*'
        tags: [ 'console.command' ]


# add more services, or override services that need manual wiring
#    TestBundle\ExampleClass:
#        arguments:
#            - "@service_id"
#            - "plain_value"
#            - "%parameter%"
 